name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        optimize: [Debug, ReleaseFast]
        include:
          - algo: vanilla
            iters: 10000
          - algo: cfr_plus
            iters: 10000
          - algo: lcfr
            iters: 10000
          - algo: dcfr
            iters: 10000
          - algo: mccfr
            iters: 300000
            threshold: 200

    steps:
      - uses: actions/checkout@v3

      - uses: cashapp/activate-hermit@v1
        with:
          cache: "true"

      - name: Build
        run: zig build -Doptimize=${{ matrix.optimize }}

      - name: Test ${{ matrix.algo }}
        run: ./zig-out/bin/cfr-leduc --algo=${{ matrix.algo }} --max-iters=${{ matrix.iters }} --threshold=${{ matrix.threshold || 100 }} --no-self-play
